### ISSUE TITLE
Traceback (most recent call last

### ISSUE THREAD

**Issue by vincenty1ung** [Toperlock/sing-box-subscribe#100]
### 描述

Traceback (most recent call last):
  File "/Users/xx/Developer/code/python_code/sing-box-subscribe/main.py", line 1, in <module>
    import json, os, tool, time, requests, sys, importlib, argparse, yaml, ruamel.yaml
  File "/Users/xx/Developer/code/python_code/sing-box-subscribe/tool.py", line 4, in <module>
    with warnings.catch_warnings(action="ignore", category=CryptographyDeprecationWarning):
TypeError: catch_warnings.__init__() got an unexpected keyword argument 'action'

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
#97

**Comment by Toperlock** [comment]
原本vercel使用的是python 3.9，改成3.12版本导致的，重新部署
