### ISSUE TITLE
hysteria2 config格式的怎么转换

### ISSUE THREAD

**Issue by Cub0ne** [Toperlock/sing-box-subscribe#13]
第一个是我自己的clash订阅链接，格式为yaml，可以转换成功，第二个是朋友给的hysteria2配置链接，格式为json，转换失败
```
输入序号，载入对应config模板（直接回车默认选第一个配置模板）：2
选择: config_template_no_groups_tun.json
Mẫu cấu hình sử dụng: config_template_no_groups_tun.json
处理: https://*/config.yaml
Đang tải link đăng ký: https://*/config.yaml
处理: https://*/config.json
Đang tải link đăng ký: https://*/config.json
Traceback (most recent call last):
  File "/Users/cubone/Documents/workSpace/github/sing-box-subscribe/main.py", line 484, in <module>
    nodes = process_subscribes(providers["subscribes"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cubone/Documents/workSpace/github/sing-box-subscribe/main.py", line 39, in process_subscribes
    _nodes = get_nodes(subscribe['url'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cubone/Documents/workSpace/github/sing-box-subscribe/main.py", line 137, in get_nodes
    data = parse_content(content)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cubone/Documents/workSpace/github/sing-box-subscribe/main.py", line 156, in parse_content
    factory = get_parser(t)
              ^^^^^^^^^^^^^
  File "/Users/cubone/Documents/workSpace/github/sing-box-subscribe/main.py", line 165, in get_parser
    proto = tool.get_protocol(node)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cubone/Documents/workSpace/github/sing-box-subscribe/tool.py", line 219, in get_protocol
    m = re.search(r'^(.+?)://', s)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by Toperlock** [comment]
目前只支持 像sing-box有outbounds字段的json格式，其他格式不支持

**Comment by Cub0ne** [comment]
麻烦问一下有这种类型的转换器么，JSON格式的config转换为URI，他也是从别的地方搞的。。

**Comment by Toperlock** [comment]
你把这个config 发给我看看，脱敏。

**Comment by Cub0ne** [comment]
> 你把这个config 发给我看看，脱敏。


```
{
  "server": "www.baidu.com:66666",
  "auth": "google.com",
  "tls": {
    "sni": "www.bing.com",
    "insecure": true
  },
  "quic": {
    "initStreamReceiveWindow": 16777216,
    "maxStreamReceiveWindow": 16777216,
    "initConnReceiveWindow": 33554432,
    "maxConnReceiveWindow": 33554432
  },
    "fastOpen": true,
  "socks5": {
    "listen": "127.0.0.1:1080"
  },
  "transport": {
    "udp": {
      "hopInterval": "30s"
    }
  }
}
```

**Comment by Toperlock** [comment]
信息不全弄不了。

**Comment by Cub0ne** [comment]
邮箱是多少📮，发你邮箱

**Comment by Toperlock** [comment]
这个hy2的clash格式会写吗，已经支持读取本地 `.yaml` 文件，文件里面需要clash字段 `proxies`
