### ISSUE TITLE
你要明白看不了P站是你节点的问题。生成配置后不去策略组选能用的节点，能怪谁？怪你自己蠢

### ISSUE THREAD

**Issue by Toperlock** [Toperlock/sing-box-subscribe#31]

**Comment by Toperlock** [comment]
https://github.com/Toperlock/sing-box-subscribe/assets/86833913/5df6df19-edef-436d-97e9-83679dfeac17

**Comment by KINGYJL** [comment]
今天更新完之后。出现问题了。大佬。如图：![Screenshot_2024-07-01-18-51-14-941_io.nekohasekai.sfa.jpg](https://github.com/Toperlock/sing-box-subscribe/assets/150465858/6be1130f-89cc-45bf-81a6-17ef59ee0eef)

**Comment by KINGYJL** [comment]
好的。

**Comment by godfather216** [comment]
2.7.1可以本地部署
2.8.0执行python3 main.py就不行了
大佬，为什么这样哦？ macos

**Comment by Toperlock** [comment]
> 2.7.1可以本地部署 2.8.0执行python3 main.py就不行了 大佬，为什么这样哦？ macos

解决办法1：python>=3.10
解决办法2：修改 `tool.py` 的第4、5行：
![image](https://github.com/user-attachments/assets/5f11d74b-f418-419a-b0fa-0bf075ba35b6)

**Comment by godfather216** [comment]
大佬：
1.Python 3.9.6，这个版本可行不，依旧不能运行失败☹️
2.tool.py第4.5行都是一样的！

**Comment by Toperlock** [comment]
> 大佬： 1.Python 3.9.6，这个版本可行不，依旧不能运行失败☹️ 2.tool.py第4.5行都是一样的！

给出报错信息

**Comment by godfather216** [comment]
> > 2.7.1可以本地部署 2.8.0执行python3 main.py就不行了大佬，为什么这样哦？ macos
> 
> 解决方法1：python>=3.10 解决方法2：修改`tool.py`的第4、5行： ![图像](https://private-user-images.githubusercontent.com/86833913/378068902-5f11d74b-f418-419a-b0fa-0bf075ba35b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjYyMDUsIm5iZiI6MTcyOTgyNTkwNSwicGF0aCI6Ii84NjgzMzkxMy8zNzgwNjg5MDItNWYxMWQ3NGItZjQxOC00MTlhLWIwZmEtMGJmMDc1YmEzNWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAzMTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMzU1OGMwYmNiNTdiODQ4ZmYzZDE4OWE1MjE3MTk3YTAzZjJlMjM3YzAyNzA4YWY3NDQ2YTFlNzlkOWRlN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wNmybeKRSGpCvCyfhw00cbASxiM9fvo0ELqQnOTl1NI)

Traceback (most recent call last):
  File "/Users/wusheng/Documents/sing-box-subscribe-no-flask-2.8.0/main.py", line 1, in <module>
    import json, os, tool, time, requests, sys, urllib, importlib, argparse, yaml
  File "/Users/wusheng/Documents/sing-box-subscribe-no-flask-2.8.0/tool.py", line 1, in <module>
    import base64,requests,random,string,re,chardet
ModuleNotFoundError: No module named 'requests'

**Comment by Toperlock** [comment]
怀疑你有用虚拟环境，请切换python版本
或者安装requests库 `pip3 install requests`
